# Generated by Django 2.2.4 on 2019-09-03 12:05

from django.db import migrations, models
class Migration(migrations.Migration):
   initial = True
   dependencies = [
   ]
   operations = [
       migrations.CreateModel(
           name='Taste_note',
           fields=[
               ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
               ('user_id', models.CharField(max_length=30)),
               ('name', models.CharField(max_length=100)),
               ('comment', models.CharField(max_length=200)),
               ('stars_taste', models.FloatField()),
               ('stars_costvalue', models.FloatField()),
               ('img_path', models.CharField(max_length=1000)),
               ('create_at', models.DateTimeField(auto_now_add=True)),
               ('update_at', models.DateTimeField(auto_now=True)),
           ],
       ),
   ]
