# Generated by Django 2.2.4 on 2019-09-07 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suldocs', '0002_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Taste_note',
            new_name='TasteNoteModel',
        ),
        migrations.RenameField(
            model_name='tastenotemodel',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='tastenotemodel',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='affiliation',
        ),
        migrations.RemoveField(
            model_name='user',
            name='iam_key',
        ),
        migrations.RemoveField(
            model_name='user',
            name='iam_value',
        ),
    ]
